### ISSUE TITLE
SuppressMessage 특성 한 줄로 표기

### ISSUE THREAD

**Issue by jwChung** [envicase/ReactiveMvvm#23]
code-analysis 경고를 해결하기 위한 SuppressMessage 특성은 현재 제한된 컬럼 안에서 작성되고 있습니다. 계속 봐야할 만큼 중요한 메세지가 아니라는 관점에서 제한된 컬럼을 넘어가도 한 줄로 표기하는게 코드를 읽는데 도움이 될 것 같습니다.

그래서 제안드립니다.
1. 앞으로 작성하는 SuppressMessage는 한 줄로 표기한다.
2. 현재 여러 줄로 표기된 SuppressMessage는 차츰 한 줄로 바꿔나간다.

**Comment by jwChung** [comment]
@gyuwon 확인하시고 특별한 의견없으시면, 동의의 의미로 이 이슈 닫아주세요.

**Comment by gyuwon** [comment]
앞으로 눈에 띄는 기존 것들에 대해서는 그때 그때 수정하는 것으로 하겠습니다.
