### ISSUE TITLE
코드 컨벤션 문의

### ISSUE THREAD

**Issue by gongdo** [envicase/ReactiveMvvm#29]
대체로 거의 대부분의 코드 컨벤션에 감탄했습니다. 코드 컨벤션은 어느 정도 '취향'이 반영되는 부분이므로 일관성만 있다면 문제가 없겠지요. 다만 약간의 의문이 드는 부분이 있어서 어떤 의견을 가지고 있는지 문의합니다.

두가지 사항에서 의문이 있는데요,
1. 클래스레벨 로컬 필드에 _(under score) prefix 사용
2. 테스트 메서드 이름에도 pascal-case를 사용할 때 가독성

[1]`_`prefix는 그것이 클레스레벨 필드라는 '의미'를 담고 있으며 이것은 'mField', 'm_Field'와 동일한 용법이 아닐까요?

물론 이것을 사용하지 않았을 때 메서드 스콥에서 이름이 겹칠 경우가 종종 발생하고 이 때마다 구분하여 `this`를 붙여줘야 하는 단점도 있습니다.

[2]'메서드의 이름은 pascal-case를 사용한다'의 원칙에는 공감합니다. 그런데 테스트의 메서드는 '문장'형식으로 씌여지고 이 때는 pascal-case가 되려 가독성을 해친다고 생각합니다. 이것은 어쩌면 훈련이나 숙련도의 문제일수도 있겠지만 여하튼 제 경우엔 3-4단어가 넘어갈 경우 공백을 `_`로 대체한 형식이 빠르게 읽기는 편했습니다.

```
public void CoalesceReturnsLeftForNonCoalescable() //...
//vs
public void Coalesce_returns_left_for_non_Coalescable() //...
```

**Comment by jwChung** [comment]
아래와 같이 말씀하신 부분에 공감을 하면서,
> 일관성만 있다면 문제가 없겠지요. 

1. 클래스레벨 로컬 필드에 _(under score) prefix 사용

    **저는 팀의 컨벤션을 따른 것이고** 개인 취향은 [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx)에서 제시하는 것처럼 under score를 사용하지 않는 것을 좋아합니다.

    그 이유는 Framework Design Guidelines에서 말하는 것처럼 언어에 국한되 네이밍을 피하기 위함도 있지만 아래와 같이 어떤 멤버를 사용할 때 그 멤버가 어디 속해있는지 먼저 알려주는 것이 저는 좋더라구요. 그래서 static 멤버일지라도 앞에도 클래스명을 사용하는 것을 좋아합니다. 더욱이 아래 두번 째라인처럼 static 멤버가 되고 있는 클래스에 속할지라도 앞에 클래스명 기입합니다.

	```c#
 	this.Method();
	ThisClassName.StaticMethod(); 
	ClassName.StaticMethod();
	this.memberField.Method();
	``` 
	under score를 사용하는 관점에서 보면 아래와 같이 표기될 것 같네요.

	```c#
	Method();
	StaticMethod();
	ClassName.StaticMethod();
	_memberField.Method();
	```
    위 두 스타일을 놓고 어느 것이 좋다라고는 말할 수 없을 것 같습니다.

2. 한때는 저도 @gongdo 님이 말씀하신는 것처럼 테스트명에 under score를 사용한적이 있습니다. 읽기는 조금 쉬워지는 것 같은데 반대로 이름이 조금 길어지는 경향이 있고, 또 under score 사용으로 느낌에 완벽한 문장같은 느낌을 주어 관사같은 것도 왠지 사용해야할 것 같고, 그래서 더욱 테스트명이 길어지는 그런 문제가 있었습니다.  
테스트명의 PascalCase사용에 익숙해져서 읽기 불편한 걸 못 느끼고 있다라고 말씀드리는게 정답인 것 같습니다.

**Comment by gongdo** [comment]
1.의 경우엔 팀이 어떤 관점인지 궁금했고
2.의 경우엔 테스트명에 언더스코어를 사용하면 관사나 정확한 문장까지 쓰도록 압박하는 단점이 있겠네요. 그럴 필요가 없다는건 명백하고요.
답변 감사합니다.

**Comment by jwChung** [comment]
@gongdo 1번의 경우는 @gyuwon 님 의견을 들으시는게 좋을 것 같네요.

**Comment by gyuwon** [comment]
1번은 @jwChung 님의 취향이 3~4년 전에 제가 가졌던 취향과 거의 일치합니다. 그러다 3.5 이후의 BCL 코드를 많으 들여다 보면서 underscore에 익숙해졌죠. `this.`에 비해 짧으면서도 의미 전달력은 약하지 않은 느낌이었습니다. 원 질문과는 벗어나지만 정적 멤버사용에 형식이름을 항상 사용하는 것도 즐겼다가 읽기 불편한 경우에만 명시하게 되었습니다.

2번도 @jwChung 님의 의견과 거의 같은 입장입니다. 하지만 snake notation이 분명 읽기 쉬운 부분이 있고 이슈가 제기 된다면 변경을 고려해 볼 수 있다고 생각합니다.

@gongdo

**Comment by gongdo** [comment]
@gyuwon 말씀드렸다시피 이것은 수정이 필요한 이슈가 아닌 궁금함이었습니다.
커미터분들께서 컨벤션에 통일을 이루고 있다면 문제는 전혀 없습니다.
