### ISSUE TITLE
dnx를 고려한 프로젝트 구성

### ISSUE THREAD

**Issue by gongdo** [envicase/ReactiveMvvm#30]
dnx는 쿨합니다. **정말로 쿨합니다.**
빠르든 늦든 Reactive-MVVM도 dnx에 대응하길 바랍니다.

그런 점에서 프로젝트 구성이 이런 방식이면 좋겠습니다. ([ASP.NET 5 MVC](https://github.com/aspnet/Mvc) 참고)

```
[Root]
+[samples]
+[src]
+[test]
-ReactiveMvvm.sln    # for .NET
-global.json         # for dnx
```

여기에서 당장 dnx에 대응하는 항목들을 만들 필요는 없지만 구성만이라도 잡아두면 추후 마이그레이션이 쉬워질 것입니다.

**Comment by jwChung** [comment]
@gongdo 저는 DNX를 떠나서 개인적으로는 말씀하시는 폴더구조를 사용하고 있습니다.(예 [Funz](https://github.com/jwChung/Funz) )

DNX와 폴더구조가 어떤 관계가 있는지 제가 조금 더 알아봐야할 것 같네요. 아래 문서를 보면 될까요?
https://github.com/aspnet/Home/wiki/DNX-structure

**Comment by gongdo** [comment]
물론 DNX가 폴더 구조를 강요하는건 아니고 이것도 일종의 컨벤션이니 규칙을 정하기만 하면 됩니다.
즉, 지금 구조로도 DNX를 적용하는데 문제가 있는건 아닙니다.

다만 DNX로 만들어지는 프로젝트들의 구조가 대체로 위에서 제안한 형식을 따르고 있고 .NET 프로젝트에 적용하는 것 역시 문제가 없어보입니다. 또한 .sln파일은 src폴더와 분리되어 있는게 더 깔끔하다고 생각합니다.

**Comment by jwChung** [comment]
@gongdo 아 그렇군요. 저도 깔끔하다는 생각에 찬성하는 입장이구요.

현재의 폴더 구조를 만드신 @gyuwon 님의 의견이 필요할 것 같네요.

**Comment by gyuwon** [comment]
저도 나쁘지 않다고 생각됩니다. @gongdo @jwChung

**Comment by jwChung** [comment]
@gyuwon @gongdo  그럼 이 이슈는 진행하는 것으로 하겠습니다.

**Comment by gongdo** [comment]
이 PR은 폴더 구성을 변경하므로 #1 과 동시에 머지할 수 없겠지요.
@jwChung @gyuwon 확인바랍니다.
