### ISSUE TITLE
Coalescer 클래스관련

### ISSUE THREAD

**Issue by jwChung** [envicase/ReactiveMvvm#4]
`Coalescer`에서 `DefaultCoalescer`를 사용할 수 있도록 Default를 제공하고 있습니다.
여기서 `Coalescer`가 abstract인 이유가 무엇인가요? 현재의 구현이라면,  abstract일 필요는 없을 것 같다는 생각이 들어서요. 그냥 특정 클래스에서 `ICoalescer`를 구현하고 `Coalescer.Default`를 그냥 사용하면 되지 않을까해서요.

**Comment by gyuwon** [comment]
처음에는 저도 그렇게 코딩했다가 `EqualityComparer<T>` 클래스와 디자인을 일치시키는 것이 어떨까하는 생각에 지금의 디자인으로 결정했습니다. 제기하신 이슈는 `EqualityComparer<T>` 클래스에서도 동일하게 적용할 수 있는 문제인데 왜 그랬는지는 저도 잘 모르겠네요.

**Comment by jwChung** [comment]
그렇군요. 저도 한번 `EqualityComparer<T>` 클래스를 살펴봤는데, abstract이유가 아래와 같이 `IEqualityComparer`를 explicit 인터페이스로 구현한 것을 제공하기 위함이 아닐까합니다. `EqualityComparer<T>`을 상속받은 클래스에서는 `IEqualityComparer<T>` 관련 멤버만 구현하면 되는 이점이 있겠네요.

```c#
    [__DynamicallyInvokable]
    int IEqualityComparer.GetHashCode(object obj)
    {
      if (obj == null)
        return 0;
      if (obj is T)
        return this.GetHashCode((T) obj);
      ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidArgumentForComparison);
      return 0;
    }

    [__DynamicallyInvokable]
    bool IEqualityComparer.Equals(object x, object y)
    {
      if (x == y)
        return true;
      if (x == null || y == null)
        return false;
      if (x is T && y is T)
        return this.Equals((T) x, (T) y);
      ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidArgumentForComparison);
      return false;
    }
```

**Comment by gyuwon** [comment]
아 그렇군요. 그건 몰랐었네요. `Coalescer<T>` 클래스는 해당 이슈가 없으니 `DefaultCoalescer<T>`를 둘 필요 없이 코드를 병합하는 것이 더 좋겠네요.

**Comment by jwChung** [comment]
네 저도 그게 좋을 것 같습니다. 승인의 의미로 제가 ready 붙여 놓겠습니다.

**Comment by jwChung** [comment]
@gyuwon help wanted 라벨을 jump in라는 이름으로 변경했습니다. jump in이라는 뜻이 더 명확한 것 같아서요. 이 이슈가 jump in에 속하지 않을까 싶네요.

**Comment by gyuwon** [comment]
이 작업을 진행하면서 `_default` 필드를 제거하고 `Default` 속성에 자동속성 초기화를 적용하는 것도 좋겠습니다.
