### ISSUE TITLE
Model<TId> abstract 를 interface로 전환 고려

### ISSUE THREAD

**Issue by jwChung** [envicase/ReactiveMvvm#5]
현재 `Model<TId>` 모습은 abstract 보다는 interface가 어울리는 것 같습니다. 멤버 추가 계획이 있으신지 모르겠습니다.

**Comment by gyuwon** [comment]
사용성을 고려했을 때 인터페이스로 변환하는 것이 더 좋을 것 같네요.

**Comment by jwChung** [comment]
@gyuwon in progress 라벨 자동으로 붙은건가요?
question에서 ready단계로 발전했다고 보고 question 라벨 제거했습니다.
